### ISSUE TITLE
feature: missing type `repository_ruleset`

### ISSUE THREAD

**Issue by rbtcollins** [cbrgm/githubevents#94]
repository_rule is [defined](https://docs.github.com/en/webhooks/webhook-events-and-payloads#repository_ruleset). 

I'm not sure if you're using code generation or artisanal definitions, but would be willing to make a patch, unless new types are super easy for you :)

**Comment by cbrgm** [comment]
Heyho,

added the necessary parameters [here](https://github.com/cbrgm/githubevents/blob/9e8da25ac4b6cf1e335c9cf2461e6c53e30926ba/gen/template_params.go#L789). Sadly the event type is not available in the main google/go-github repository and has to be added there first. You can raise and issue there if you want, could be a cool first contributions, otherwise I'll do it probably in the next days.

Cheers!

**Comment by rbtcollins** [comment]
Great, thanks! I've filed [an issue](https://github.com/google/go-github/issues/3295) which obviously doesn't do the work, but does let folk know. 

I doubt I'll get the CLA approved by legal in order to submit a patch to go-github in the short term :/. If only it was DCO or simple FLOSS.

**Comment by cbrgm** [comment]
Nice, it was merged last week. I'm waiting for the v67 release and will add the new webhook type then. Thanks for raising the issue!

**Comment by cbrgm** [comment]
It took quite a while but `repository_ruleset` events are now supported!
